version: '3'
services:
  db:
    image: postgres
    volumes:
    - /var/lib/postgresql/datadb/
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
    - "./:/var/www"
    ports:
    - "3000:3000"
    depends_on:
    - db
