default: &default
  adapter: postgresql
  encoding: utf8
  username: postgres
  pool: 5
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: rails_kubernetes_development
  host: localhost

test:
  <<: *default
  database: rails_kubernetes_test
  host: localhost

production:
  <<: *default
  database: rails_kubernetes
